# Generated by Django 6.0.2 on 2026-03-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("content", models.TextField(blank=True, null=True, verbose_name="Содержимое")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("preview", models.ImageField(blank=True, null=True, upload_to="photo/", verbose_name="Превью")),
                ("publication_attribute", models.BooleanField(default=False, verbose_name="Опубликовать?")),
                ("number_of_views", models.IntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ["name"],
            },
        ),
    ]
