# Generated by Django 6.0.2 on 2026-04-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_product_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="publication",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Публикация"),
        ),
    ]
