# Generated by Django 6.0.2 on 2026-04-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_publication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="product",
            name="publication",
        ),
    ]
