# Generated by Django 6.0.2 on 2026-04-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_options_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default=1, max_length=150, verbose_name="Наименование"),
            preserve_default=False,
        ),
    ]
